name: Marc Graham
markdown: kramdown
#permalink: /blog/:year/:month/:day/:title
permalink: /:categories/:title # Don't show the date of the post in the URL
show_excerpts: true # Show excerpts of posts on the home page

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap # I added this to automatiacally generate a sitemap.xml
